import { database } from '@/db';
import {accountIdentity} from '@/lib/identity';
import {getData,mutate} from '@/db/service';
import {InputError} from '@/lib/account-rules';
import {ensureLaunchPlayer,launchState,launchStats,allowLaunchMutation,launchRecords} from '@/db/launch';
export const dynamic='force-dynamic';
const noCache={'Cache-Control':'no-store'};
async function handle(request:Request,write:boolean){try{const id=await accountIdentity(request.headers);if(!id)throw new InputError('Sign in to access your FragStake account.',401);const url=new URL(request.url);if(write){const origin=request.headers.get('origin');if((origin&&origin!==url.origin)||request.headers.get('sec-fetch-site')==='cross-site')throw new InputError('Request origin rejected.',403);if(!request.headers.get('content-type')?.startsWith('application/json'))throw new InputError('Use JSON for this request.');}const db=database();await ensureLaunchPlayer(db,id);let result;if(write){const raw=await request.text();if(raw.length>8192)throw new InputError('Request is too large.',413);let body;try{body=JSON.parse(raw)}catch{throw new InputError('Invalid request.')}if(!body||typeof body!=='object'||Array.isArray(body))throw new InputError('Invalid request.');allowLaunchMutation(body.action);result=await mutate(db,id,body)}else {const action=url.searchParams.get('action')||'state';if(action==='state')result=await launchState(db,id);else if(action==='leaderboard'){const records=await launchRecords(db,null);result={players:records.leaders,total:records.leaders.length,page:0};}else {result=await getData(db,id,url);if(action==='platform')result={...result,ratings:[]};if(action==='player'&&'player' in result)result={...result,stats:await launchStats(db,(result.player as {id:string}).id)};}}if(result&&typeof result==='object'){if('player' in result&&result.player)result={...result,player:{...result.player,balance:0}};if('transactions' in result)result={...result,transactions:[],matches:[],active:null,stats:await launchStats(db,id)};if('platform' in result&&result.platform)result={...result,platform:{...result.platform,ratings:[]}};}return Response.json(result,{headers:noCache})}catch(error){if(error instanceof InputError)return Response.json({error:error.message},{status:error.status,headers:noCache});console.error('Account request failed',String(error));return Response.json({error:'We could not save or load your account. Please try again.'},{status:500,headers:noCache})}}
export function GET(request:Request){return handle(request,false)}
export function POST(request:Request){return handle(request,true)}
