'use client';
import {useEffect,useRef,useState} from 'react';
import {Crosshair,ArrowLeft,VolumeX} from 'lucide-react';
import {type MatchConfig,type Result,killBalance,deathBalance,duelPayout} from '@/lib/game-rules';
const MAP=['1111111111111111','1000000000000001','1000000100000001','1001100100110001','1000000000000001','1000000000000001','1100011000100001','1000000000100001','1000000000000001','1001000010000001','1001000010000001','1000000000000001','1000011000110001','1000000000000001','1000000000000001','1111111111111111'];
const SPAWNS=[[2.5,2.5],[13.5,13.5],[2.5,13.5],[13.5,2.5],[8.5,5.5],[4.5,8.5],[11.5,8.5],[7.5,13.5],[8.5,1.5],[1.5,7.5]];
type Actor={x:number;y:number;hp:number;team:number;cooldown:number;respawn:number;angle:number;name:string;balance:number};
type Hud={hp:number;ammo:number;kills:number;deaths:number;time:number;balance:number;score:number;enemyScore:number;feed:string;reloading:boolean};
export default function Arena({config,onFinish}:{config:MatchConfig;onFinish:(r:Result)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null);const controls=useRef(new Set<string>());const finish=useRef(onFinish);finish.current=onFinish;
 const [active,setActive]=useState(false);const [hud,setHud]=useState<Hud>({hp:100,ammo:24,kills:0,deaths:0,time:180,balance:config.balance,score:0,enemyScore:0,feed:'',reloading:false});const [locked,setLocked]=useState(false);const leave=useRef<()=>void>(()=>{});
 useEffect(()=>{if(!active||!canvas.current)return;const el=canvas.current;const ctx=el.getContext('2d');if(!ctx)return;
 let w=0,h=0,frame=0,last=performance.now(),elapsed=0,clock=0,angle=.4,ammo=24,reload=0,kills=0,deaths=0,score=0,enemyScore=0,balance=config.balance,feed='',feedTime=0,shotFlash=0,damageFlash=0,ended=false,pause=true;
 const player:Actor={x:2.5,y:2.5,hp:100,team:0,cooldown:0,respawn:0,angle:0,name:'You',balance};
 const count=config.mode==='duel'?(config.team==='2v2'?3:1):9;
 const bots:Actor[]=Array.from({length:count},(_,i)=>({x:SPAWNS[i+1][0],y:SPAWNS[i+1][1],hp:100,team:config.mode==='duel'?(config.team==='2v2'&&i===2?0:1):i+1,cooldown:1+Math.random()*2,respawn:0,angle:Math.random()*Math.PI*2,name:config.mode==='duel'&&config.team==='2v2'&&i===2?'Ally bot':'Bot '+(i+1),balance:100}));
 const actors=[player,...bots];const solid=(x:number,y:number)=>!MAP[Math.floor(y)]||MAP[Math.floor(y)][Math.floor(x)]!=='0';
 const ray=(x:number,y:number,a:number,max=24)=>{let d=.02;while(d<max&&!solid(x+Math.cos(a)*d,y+Math.sin(a)*d))d+=.04;return d};
 const visible=(a:Actor,b:Actor)=>ray(a.x,a.y,Math.atan2(b.y-a.y,b.x-a.x),Math.hypot(b.x-a.x,b.y-a.y))>=Math.hypot(b.x-a.x,b.y-a.y)-.08;
 const move=(a:Actor,dx:number,dy:number)=>{if(!solid(a.x+dx+Math.sign(dx)*.18,a.y))a.x+=dx;if(!solid(a.x,a.y+dy+Math.sign(dy)*.18))a.y+=dy};
 const end=(reason:string,won=false,draw=false)=>{if(ended)return;ended=true;controls.current.clear();if(config.mode==='duel')balance+=duelPayout(won,draw);if(document.pointerLockElement===el)document.exitPointerLock();finish.current({kills,deaths,balance,reason,won,score,enemyScore})};
 leave.current=()=>end(config.mode==='duel'?'Duel forfeited':'Left the arena');
 const frag=(victim:Actor,killer:Actor)=>{if(victim.hp<=0)return;victim.hp=0;victim.respawn=2;feed=killer.name+' eliminated '+victim.name;feedTime=3;
 if(victim===player){deaths++;balance=deathBalance(balance,config.mode,config.rate);damageFlash=.8}else victim.balance=deathBalance(victim.balance,config.mode,config.rate);
 if(killer===player){kills++;balance=killBalance(balance,config.mode,config.rate)}else killer.balance=killBalance(killer.balance,config.mode,config.rate);
 if(config.mode==='duel'){if(killer.team===0)score++;else enemyScore++;if(score>=5||enemyScore>=5)end(score>=5?'Duel won':'Duel lost',score>=5)}
 if(config.mode==='ffa'&&balance<config.rate)end('Not enough credits for another death');};
 const shoot=()=>{if(pause||ended||reload>0||player.hp<=0||player.cooldown>0)return;if(ammo<=0){reload=1.4;return}ammo--;player.cooldown=.18;shotFlash=.1;
 let target:Actor|undefined,near=100;for(const b of bots){if(b.hp<=0||b.team===player.team)continue;const dist=Math.hypot(b.x-player.x,b.y-player.y),bearing=Math.atan2(b.y-player.y,b.x-player.x);const da=Math.atan2(Math.sin(bearing-angle),Math.cos(bearing-angle));if(Math.abs(da)<Math.atan2(.34,dist)&&dist<near&&visible(player,b)){target=b;near=dist}}if(target){target.hp-=34;if(target.hp<=0){target.hp=1;frag(target,player)}}};
 const keydown=(e:KeyboardEvent)=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyR'].includes(e.code)){e.preventDefault();controls.current.add(e.code)}if(e.code==='KeyR'&&ammo<24&&!reload)reload=1.4;};const keyup=(e:KeyboardEvent)=>controls.current.delete(e.code);
 const mouse=(e:MouseEvent)=>{if(document.pointerLockElement===el)angle+=e.movementX*.0025};
 const lock=()=>{const isLocked=document.pointerLockElement===el;setLocked(isLocked);if(!isLocked){pause=true;controls.current.clear()}};
 const down=(e:PointerEvent)=>{if(e.pointerType==='touch'){pause=false;setLocked(true);shoot()}else if(document.pointerLockElement!==el){void el.requestPointerLock()?.then(()=>{pause=false;setLocked(true)}).catch(()=>{pause=false;setLocked(true)})}else{pause=false;shoot()}};
 const blur=()=>{pause=true;setLocked(false);controls.current.clear()};
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('mousemove',mouse);window.addEventListener('blur',blur);document.addEventListener('pointerlockchange',lock);el.addEventListener('pointerdown',down);
 const respawn=(a:Actor)=>{const candidates=SPAWNS.slice().sort((p,q)=>Math.hypot(q[0]-player.x,q[1]-player.y)-Math.hypot(p[0]-player.x,p[1]-player.y));const sp=a===player?SPAWNS[Math.floor(Math.random()*SPAWNS.length)]:candidates[Math.floor(Math.random()*3)];a.x=sp[0];a.y=sp[1];a.hp=100;a.cooldown=1.5;if(a===player){ammo=24;reload=0}};
 const render=(now:number)=>{if(ended)return;const dt=Math.min((now-last)/1000,.04);last=now;const rect=el.getBoundingClientRect();if(w!==Math.floor(rect.width)||h!==Math.floor(rect.height)){w=Math.floor(rect.width);h=Math.floor(rect.height);el.width=w;el.height=h}
 if(!pause){elapsed+=dt;player.cooldown=Math.max(0,player.cooldown-dt);if(reload>0){reload-=dt;if(reload<=0)ammo=24}if(controls.current.has('KeyR')&&ammo<24&&reload<=0)reload=1.4;
 if(player.hp>0){const speed=3.2*dt,forward=Number(controls.current.has('KeyW')||controls.current.has('ArrowUp'))-Number(controls.current.has('KeyS')||controls.current.has('ArrowDown')),side=Number(controls.current.has('KeyD'))-Number(controls.current.has('KeyA'));angle+=(Number(controls.current.has('ArrowRight'))-Number(controls.current.has('ArrowLeft')))*dt*2;move(player,(Math.cos(angle)*forward+Math.cos(angle+Math.PI/2)*side)*speed,(Math.sin(angle)*forward+Math.sin(angle+Math.PI/2)*side)*speed);if(controls.current.has('Space'))shoot()}
 for(const a of actors){if(a.hp<=0){a.respawn-=dt;if(a.respawn<=0&&(config.mode!=='ffa'||a===player||a.balance>=config.rate))respawn(a);continue}if(a===player)continue;a.cooldown-=dt;
 const enemies=actors.filter(b=>b!==a&&b.hp>0&&b.team!==a.team).sort((b,c)=>Math.hypot(b.x-a.x,b.y-a.y)-Math.hypot(c.x-a.x,c.y-a.y));const target=enemies.find(b=>visible(a,b));if(target){const dist=Math.hypot(target.x-a.x,target.y-a.y);a.angle=Math.atan2(target.y-a.y,target.x-a.x);if(dist>3)move(a,Math.cos(a.angle)*dt*1.15,Math.sin(a.angle)*dt*1.15);if(dist<9&&a.cooldown<=0){a.cooldown=1.1+Math.random();if(Math.random()>.36){target.hp-=16;if(target===player)damageFlash=.18;if(target.hp<=0){target.hp=1;frag(target,a)}}}}else{if(Math.random()<dt*.7)a.angle+=Math.random()*2-1;const ox=a.x,oy=a.y;move(a,Math.cos(a.angle)*dt*1.2,Math.sin(a.angle)*dt*1.2);if(Math.abs(ox-a.x)+Math.abs(oy-a.y)<dt*.4)a.angle+=Math.PI*.55}}
 if(elapsed>=180){if(config.mode==='duel')end(score===enemyScore?'Draw — stake returned':score>enemyScore?'Duel won':'Duel lost',score>enemyScore,score===enemyScore);else end('Round complete',kills>deaths)}feedTime-=dt;shotFlash-=dt;damageFlash-=dt;
 }
 const horizon=h*.48;const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#111b20');sky.addColorStop(1,'#64716a');ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon);const ground=ctx.createLinearGradient(0,horizon,0,h);ground.addColorStop(0,'#333c30');ground.addColorStop(1,'#11180f');ctx.fillStyle=ground;ctx.fillRect(0,horizon,w,h);
 const fov=Math.PI/2.6,projection=w/(2*Math.tan(fov/2)),depths:number[]=[];for(let x=0;x<w;x+=3){const offset=Math.atan((x-w/2)/projection),a=angle+offset,d=ray(player.x,player.y,a)*Math.cos(offset),height=projection/d;depths[x]=d;const hitX=player.x+Math.cos(a)*d/Math.cos(offset),hitY=player.y+Math.sin(a)*d/Math.cos(offset),edge=Math.min(hitX%1,1-hitX%1,hitY%1,1-hitY%1),shade=Math.max(22,Math.floor(135/(1+d*.12)));ctx.fillStyle='rgb('+Math.floor(shade*.91)+','+shade+','+Math.floor(shade*.79)+')';ctx.fillRect(x,horizon-height/2,3,height);ctx.fillStyle='#00000029';ctx.fillRect(x,horizon+height*.31,3,height*.035);ctx.fillRect(x,horizon-height*.39,3,height*.02);if(edge<.045){ctx.fillStyle='#0e170c35';ctx.fillRect(x,horizon-height/2,3,height)}if(Math.floor(hitX+hitY)%5===0){ctx.fillStyle='#d7db8a';ctx.fillRect(x,horizon-height*.28,3,height*.025)}}
 const sorted=bots.filter(b=>b.hp>0).map(b=>({b,dist:Math.hypot(b.x-player.x,b.y-player.y)})).sort((a,b)=>b.dist-a.dist);for(const {b,dist} of sorted){const da=Math.atan2(Math.sin(Math.atan2(b.y-player.y,b.x-player.x)-angle),Math.cos(Math.atan2(b.y-player.y,b.x-player.x)-angle));if(Math.abs(da)>fov*.8)continue;const size=projection/(dist*Math.cos(da)),sx=w/2+Math.tan(da)*projection;const friendly=b.team===0,col=friendly?'#b6e76a':'#f19a63';for(let x=Math.max(0,Math.floor((sx-size*.19)/3)*3);x<Math.min(w,sx+size*.19);x+=3){if((depths[x]||100)<dist*Math.cos(da))continue;const ratio=Math.abs(x-sx)/size;ctx.fillStyle=col;if(ratio<.11)ctx.fillRect(x,horizon-size*.38,3,size*.19);ctx.fillStyle=friendly?'#647b48':'#845c42';ctx.fillRect(x,horizon-size*.15,3,size*.39);ctx.fillStyle='#222b27';if(ratio>.03&&ratio<.15)ctx.fillRect(x,horizon+size*.22,3,size*.28);ctx.fillStyle=col;ctx.fillRect(x,horizon-size*.06,3,size*.055)}if(sx>0&&sx<w&&visible(player,b)){ctx.fillStyle=col;ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(b.name,sx,horizon-size*.45);ctx.fillRect(sx-18,horizon-size*.42,36*b.hp/100,3)}}
 // First-person weapon geometry is part of the playable renderer.
 const sway=Math.sin(elapsed*8)*(controls.current.size?4:1),gx=w*.63,gy=h+12+sway+(reload>0?70:0);ctx.fillStyle='#111814';ctx.beginPath();ctx.moveTo(gx-42,gy);ctx.lineTo(gx-22,gy-128);ctx.lineTo(gx+3,gy-173);ctx.lineTo(gx+31,gy-173);ctx.lineTo(gx+50,gy-117);ctx.lineTo(gx+103,gy);ctx.fill();ctx.fillStyle='#465348';ctx.fillRect(gx+1,gy-170,28,111);ctx.fillStyle='#212c23';ctx.fillRect(gx+8,gy-180,15,56);ctx.fillStyle='#c8ef57';ctx.fillRect(gx+11,gy-153,8,4);ctx.fillStyle='#758571';ctx.fillRect(gx-19,gy-75,12,52);if(shotFlash>0){ctx.fillStyle='#fff8bd';ctx.beginPath();ctx.arc(gx+15,gy-180,18,0,Math.PI*2);ctx.fill()}
 ctx.strokeStyle='#deffa5';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(w/2-11,h/2);ctx.lineTo(w/2-4,h/2);ctx.moveTo(w/2+4,h/2);ctx.lineTo(w/2+11,h/2);ctx.moveTo(w/2,h/2-11);ctx.lineTo(w/2,h/2-4);ctx.moveTo(w/2,h/2+4);ctx.lineTo(w/2,h/2+11);ctx.stroke();if(damageFlash>0){ctx.fillStyle='#c52a252c';ctx.fillRect(0,0,w,h)}if(player.hp<=0){ctx.fillStyle='#071006aa';ctx.fillRect(0,0,w,h);ctx.fillStyle='#edf8df';ctx.font='bold 24px Arial';ctx.textAlign='center';ctx.fillText('RESPAWNING IN '+Math.ceil(player.respawn),w/2,h/2-30)}
 // Compact minimap reveals the local player's position and arena walls.
 const ms=Math.min(5,w/90);ctx.fillStyle='#0a120bb8';ctx.fillRect(12,12,16*ms,16*ms);ctx.fillStyle='#82906c';MAP.forEach((row,y)=>[...row].forEach((v,x)=>{if(v==='1')ctx.fillRect(12+x*ms,12+y*ms,ms-1,ms-1)}));ctx.fillStyle='#d4fa45';ctx.beginPath();ctx.arc(12+player.x*ms,12+player.y*ms,3,0,7);ctx.fill();
 clock+=dt;if(clock>.1){clock=0;setHud({hp:Math.max(0,player.hp),ammo,kills,deaths,time:Math.max(0,180-Math.floor(elapsed)),balance,score,enemyScore,feed:feedTime>0?feed:'',reloading:reload>0})}frame=requestAnimationFrame(render)};
 frame=requestAnimationFrame(render);return()=>{ended=true;cancelAnimationFrame(frame);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('mousemove',mouse);window.removeEventListener('blur',blur);document.removeEventListener('pointerlockchange',lock);el.removeEventListener('pointerdown',down);controls.current.clear();if(document.pointerLockElement===el)document.exitPointerLock()};
 },[active,config]);
 const touch=(key:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);controls.current.add(key)},onPointerUp:()=>controls.current.delete(key),onPointerCancel:()=>controls.current.delete(key)});
 return <div className="arena-screen"><header className="arena-top"><span className="brand"><Crosshair/> SKILLCLASH</span><span>{config.mode==='practice'?'PRACTICE':config.mode==='ffa'?'CASH FFA':config.team+' DUEL'} <small>BOT ARENA · DEMO</small></span><button className="secondary" onClick={()=>active?leave.current():finish.current({kills:0,deaths:0,balance:config.balance+(config.mode==='duel'?10:0),reason:'Match cancelled',won:false,score:0,enemyScore:0})}><ArrowLeft size={16}/> Leave</button></header>
 <div className="game-viewport"><canvas ref={canvas} aria-label="First-person shooter. WASD to move, mouse or left/right arrows to aim, click or space to fire, R to reload." tabIndex={0}/>{!active?<div className="game-cover"><Crosshair size={42}/><span className="eyebrow">THE FOUNDRY</span><h1>READY TO DROP IN?</h1><p>{config.mode==='duel'?'First side to 5 eliminations.':'Three minutes. Make every shot count.'}<br/>{config.mode==='duel'&&config.team==='2v2'?'One ally bot and two opponents.':'You are playing against '+(config.mode==='duel'?'one bot.':'nine bots.')}</p><div className="key-help"><span><kbd>W A S D</kbd> Move</span><span><kbd>MOUSE / ← →</kbd> Aim</span><span><kbd>CLICK / SPACE</kbd> Fire</span><span><kbd>R</kbd> Reload</span></div><button className="primary" onClick={()=>setActive(true)}>Enter arena</button><small>Demo credits only · Audio off</small></div>:<>{!locked&&<div className="resume-hint">Click the arena to play · Esc to pause<br/><small>Touch: tap the arena, then use the controls below</small></div>}<div className="game-timer">{Math.floor(hud.time/60)}:{String(hud.time%60).padStart(2,'0')}<small>{config.mode==='duel'?hud.score+' : '+hud.enemyScore:'FFA · 10 combatants'}</small></div><div className="kill-feed">{hud.feed}</div><div className="game-hud"><div><b>{hud.hp}</b><span>HEALTH</span></div><div><b>{hud.kills} <i>/ {hud.deaths}</i></b><span>KILLS / DEATHS</span></div><div><b>{config.mode==='practice'?'FREE':'€'+hud.balance.toFixed(2)}</b><span>{config.mode==='duel'?'STAKE RESERVED':'DEMO BALANCE'}</span></div><div><b>{hud.reloading?'…':hud.ammo}<i> / 24</i></b><span>{hud.reloading?'RELOADING':'AMMO'}</span></div></div></> }</div>
 {active&&<div className="touch-controls"><button {...touch('ArrowLeft')}>↶</button><button {...touch('KeyW')}>↑</button><button {...touch('KeyS')}>↓</button><button {...touch('ArrowRight')}>↷</button><button {...touch('Space')}>FIRE</button><button {...touch('KeyR')}>R</button></div>}
 <div className="arena-bottom"><span>WASD to move · Mouse or arrows to aim · Click or Space to fire · R to reload</span><span><VolumeX size={14}/> Bot practice · No real money</span></div></div>
}

