'use client';
import { useEffect, useState } from 'react';
import Arena from './arena';
import {canEnter, type MatchConfig, type Result} from '@/lib/game-rules';
import { Crosshair, ArrowUpRight, ArrowRight, Target, Swords, Zap, Wallet, ShieldCheck, Gamepad2, CircleHelp, Trophy } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
type Mode = 'practice' | 'ffa' | 'duel';
const tiers = [{name:'Beginner',rate:2,desc:'Find your footing',icon:Target},{name:'Contender',rate:5,desc:'Raise the stakes',icon:Zap},{name:'Pro',rate:10,desc:'Every shot matters',icon:Trophy}];
export default function Home(){
 const [mode,setMode]=useState<Mode>('ffa'); const [tier,setTier]=useState(0); const [team,setTeam]=useState('1v1'); const [info,setInfo]=useState(false); const [wallet,setWallet]=useState(false); const [launch,setLaunch]=useState(false);
 const [balance,setBalance]=useState(100);const [game,setGame]=useState<MatchConfig|null>(null);const [result,setResult]=useState<Result|null>(null);const [history,setHistory]=useState<{name:string;delta:number;date:string}[]>([]);const [loaded,setLoaded]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('skillclash-demo-v1')||'null');if(saved&&Number.isFinite(saved.balance)&&saved.balance>=0){setBalance(saved.balance);if(Array.isArray(saved.history))setHistory(saved.history.filter((v:unknown)=>v&&typeof v==='object'&&'delta' in v&&Number.isFinite(v.delta)&&'name' in v&&typeof v.name==='string'&&'date' in v&&typeof v.date==='string').slice(0,10))}}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded){try{localStorage.setItem('skillclash-demo-v1',JSON.stringify({balance,history}))}catch{}}},[balance,history,loaded]);
 function start(){const c:MatchConfig={mode,rate:tiers[tier].rate,team:team==='2v2'?'2v2':'1v1',balance};if(!canEnter(c))return;setLaunch(false);setResult(null);if(mode==='duel'){c.balance-=10;setBalance(c.balance)}setGame(c)}
 function finishMatch(r:Result){if(!game)return;const startBalance=game.balance+(game.mode==='duel'?10:0);setBalance(r.balance);if(r.reason!=='Match cancelled')setHistory(h=>[{name:game.mode==='practice'?'Practice':game.mode==='ffa'?'Cash FFA':game.team+' duel',delta:r.balance-startBalance,date:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})},...h].slice(0,10));setResult({...r,balance:r.balance});setGame(null)}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'configure_match',title:'Configure a SkillClash match',description:'Select a demo mode and open its pre-match review. Does not spend credits or start gameplay.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['practice','ffa','duel']},tier:{type:'integer',minimum:0,maximum:2},team:{type:'string',enum:['1v1','2v2']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const v=input as {mode:Mode;tier?:number;team?:string};if(!v||!['practice','ffa','duel'].includes(v.mode)||(v.tier!==undefined&&(!Number.isInteger(v.tier)||v.tier<0||v.tier>2))||(v.team!==undefined&&!['1v1','2v2'].includes(v.team)))throw new Error('Invalid match configuration');if(game)throw new Error('Leave the current match first');setMode(v.mode);if(v.tier!==undefined)setTier(v.tier);if(v.team)setTeam(v.team);setLaunch(true);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {mode:v.mode,status:'ready_for_review',demo:true}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[game]);
 if(game)return <Arena config={game} onFinish={finishMatch}/>;
 return <div className="site-shell">
 <header className="topbar">
   <a className="brand" href="/" aria-label="SkillClash home"><span className="brand-symbol"><Crosshair/></span><span>SKILL<span>CLASH</span><small>COMPETITIVE ARENA</small></span></a>
   <nav className="top-nav" aria-label="Main navigation"><span className="nav-active"><Gamepad2 size={17}/> Play</span><button onClick={()=>setWallet(true)}><Wallet size={16}/> Wallet</button><button onClick={()=>setInfo(true)}><CircleHelp size={16}/> How to play</button></nav>
   <div className="account"><button className="wallet-button" onClick={()=>setWallet(true)}><span className="wallet-label">DEMO BALANCE</span><b>€{balance.toFixed(2)}</b><span className="wallet-plus">+</span></button><div className="avatar">P1</div></div>
 </header>
 <main className="main">
   <div className="page-heading"><div><div className="eyebrow"><span className="orange-line"/> SKILLCLASH / PLAY</div><h1>CHOOSE YOUR FIGHT<span>.</span></h1></div><div className="server-status"><span/> ARENA PREVIEW <i/> <small>Bots · Demo credits</small></div></div>
   <div className="lobby-layout">
     <section className={'feature feature-'+mode} aria-label="Selected game mode">
       <div className={'feature-art art-'+mode}/><div className="feature-shade"/>
       <div className="feature-label"><span/> {mode==='ffa'?'CASH FREE-FOR-ALL':mode==='duel'?'HEAD-TO-HEAD DUELS':'FREE PRACTICE'}</div>
       <div className="feature-copy"><span className="feature-kicker">{mode==='ffa'?'HIGH STAKES. PURE SKILL.':mode==='duel'?'NO BACKUP PLAN.':'YOUR WARM-UP STARTS HERE.'}</span><h2>{mode==='ffa'?<>EVERY SHOT.<br/><em>COUNTS.</em></>:mode==='duel'?<>ONE MATCH.<br/><em>ONE WINNER.</em></>:<>ZERO RISK.<br/><em>ALL SKILL.</em></>}</h2><p>{mode==='ffa'?'Earn on every elimination. Put your aim to the test.':mode==='duel'?'Bring your best. The winning side takes the pot.':'Learn the arena. Land your shots. Find your edge.'}</p></div>
       <div className="feature-bottom"><div className="map-stamp"><Crosshair size={23}/><div><b>THE FOUNDRY</b><small>INDUSTRIAL · CLOSE QUARTERS</small></div></div><span className="map-format">{mode==='duel'?team:'10 PLAYER FFA'}<span>BOT ARENA</span></span></div>
       <span className="feature-corner" aria-hidden="true">SC—01</span>
     </section>
     <section className="match-panel" aria-label="Match configuration">
       <div className="match-heading"><span className="eyebrow">YOUR NEXT MATCH</span><span className="demo-badge">DEMO</span></div>
       <div className="match-title"><h2>{mode==='ffa'?'CASH FFA':mode==='duel'?'DUELS':'PRACTICE'}</h2><span>{mode==='ffa'?'01':mode==='duel'?'02':'00'}</span></div>
       <p className="setup-label">{mode==='ffa'?'Select your stakes':mode==='duel'?'Select your format':'No stakes. Just you and the arena.'}</p>
       {mode==='ffa'?<div className="tier-grid">{tiers.map((t,i)=><button className={'tier '+(tier===i?'active':'')} key={t.name} onClick={()=>setTier(i)} aria-pressed={tier===i}><span className="tier-icon"><t.icon size={20}/></span><div className="tier-name"><b>{t.name}</b><small>{t.desc}</small></div><div className="tier-rate">€{t.rate}<small>/ kill</small></div><span className="radio-dot"/></button>)}</div>:mode==='duel'?<><Tabs value={team} onValueChange={v=>setTeam(String(v))}><TabsList className="format-tabs"><TabsTrigger value="1v1"><Crosshair size={18}/>1v1</TabsTrigger><TabsTrigger value="2v2"><Swords size={18}/>2v2</TabsTrigger></TabsList></Tabs><div className="duel-pot"><span>TOTAL MATCH POT</span><b>€{team==='1v1'?20:40}<i>.00</i></b><small>{team==='1v1'?'Winner takes €20':'€20 to each winning teammate'}</small></div></>:<div className="practice-detail"><Crosshair size={48}/><div><b>LOCK IN YOUR AIM.</b><p>9 bots. Instant respawns.<br/>Unlimited chances to improve.</p></div><span>FREE TO PLAY</span></div>}
       <div className="match-bottom"><div className="stake-summary">{mode==='ffa'?<><span><small>PER KILL</small><b className="positive">+€{tiers[tier].rate}.00</b></span><span><small>PER DEATH</small><b className="negative">−€{tiers[tier].rate}.00</b></span></>:mode==='duel'?<><span><small>YOUR STAKE</small><b>€10.00</b></span><span><small>WIN CONDITION</small><b>FIRST TO 5</b></span></>:<><span><small>ENTRY</small><b className="positive">FREE</b></span><span><small>ROUND LENGTH</small><b>3 MINUTES</b></span></>}</div>
       <button className="primary play-button" onClick={()=>setLaunch(true)}><Gamepad2 size={19}/>{mode==='practice'?'START PRACTICE':mode==='ffa'?'PLAY '+tiers[tier].name.toUpperCase():'PLAY '+team+' DUEL'}<ArrowRight size={20}/></button><small className="queue-note"><ShieldCheck size={13}/> {mode==='duel'?'€10 per player · No platform fee':'Instant bot match · No queue'}</small></div>
     </section>
     <section className="modes-section" aria-label="Game modes">
       <div className="section-heading"><h2><span>01</span> FIND YOUR GAME</h2><span>WARM UP. CASH IN. FACE OFF.</span></div>
       <div className="mode-grid">{([{id:'practice',title:'PRACTICE',tag:'WARM UP',desc:'Dial in your aim. Leave the stakes behind.',icon:Crosshair,foot:'FREE TO PLAY',meta:'10 player FFA'}, {id:'ffa',title:'CASH FFA',tag:'CASH IN',desc:'Every elimination moves your balance.',icon:Zap,foot:'FROM €2 / KILL',meta:'10 player FFA'}, {id:'duel',title:'DUELS',tag:'FACE OFF',desc:'Go solo or bring a teammate. Take the pot.',icon:Swords,foot:'€10 / PLAYER',meta:'1v1 · 2v2'}] as const).map((m,i)=><button key={m.id} className={'mode-card mode-'+m.id+' '+(mode===m.id?'selected':'')} onClick={()=>setMode(m.id)} aria-pressed={mode===m.id}><div className={'mode-art art-'+m.id}/><div className="mode-shade"/><div className="card-top"><span className="mode-index">0{i+1} / {m.tag}</span><span className="mode-check">{mode===m.id?<><span/> SELECTED</>:<ArrowUpRight size={20}/>}</span></div><div className="mode-content"><span className="mode-icon"><m.icon size={22}/></span><h3>{m.title}</h3><p>{m.desc}</p></div><div className="card-bottom"><strong>{m.foot}</strong><span>{m.meta}</span><ArrowUpRight size={17}/></div></button>)}</div>
     </section>
   </div>
   <div className="demo-note"><ShieldCheck size={17}/><p><b>PLAY THE PREVIEW</b><span>Bot opponents. Demo credits. Real multiplayer and payments are not connected.</span></p><span className="demo-version">SC / ARENA 01</span></div>
   <footer><span className="footer-brand">SKILLCLASH</span><span>YOUR SKILL. YOUR GAME.</span><button onClick={()=>setInfo(true)}>Game rules <ArrowUpRight size={14}/></button></footer>
 </main>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent className="sc-dialog"><DialogTitle>Know the rules</DialogTitle><DialogDescription>Three modes, one arena. This prototype uses bots and demo credits.</DialogDescription><div className="rule"><Crosshair/><div><h3>Practice</h3><p>Free FFA. Warm up with nine bots. Kills and deaths do not change your balance.</p></div></div><div className="rule"><Zap/><div><h3>Cash FFA</h3><p>Beginner: €2, Contender: €5, Pro: €10 per kill or death. A kill credits your balance; a death deducts the same amount. A round ends if you cannot cover another death.</p></div></div><div className="rule"><Swords/><div><h3>Duels</h3><p>Each player puts in €10. First side to 5 wins. In 1v1 the winner receives €20. In 2v2 the €40 pot is split equally between the winning teammates. Leaving early forfeits the stake.</p></div></div></DialogContent></Dialog>
 <Dialog open={wallet} onOpenChange={setWallet}><DialogContent className="sc-dialog"><DialogTitle>Your demo wallet</DialogTitle><DialogDescription>Demo credits have no cash value and cannot be withdrawn.</DialogDescription><div className="wallet-amount">€{balance.toFixed(2)}</div><p>Your balance is saved on this device. Payments are not connected in this preview.</p><button className="secondary" onClick={()=>{setBalance(100);setHistory([])}}>Reset demo wallet to €100</button><div className="wallet-history">{history.length===0?<p>No matches yet. Your results will appear here.</p>:history.map((h,i)=><div key={i}><span>{h.name}<small>{h.date}</small></span><b>{h.delta>=0?"+":"−"}€{Math.abs(h.delta).toFixed(2)}</b></div>)}</div></DialogContent></Dialog>
 <Dialog open={launch} onOpenChange={setLaunch}><DialogContent className="sc-dialog"><DialogTitle>{mode==='practice'?'Practice':mode==='ffa'?tiers[tier].name+' FFA':team+' duel'}</DialogTitle><DialogDescription>The Foundry · Bot arena · Demo credits</DialogDescription><p>{mode==="practice"?"Free entry. Warm up against nine bots in a three-minute round.":mode==="ffa"?"Earn €"+tiers[tier].rate+" per kill and lose €"+tiers[tier].rate+" per death. The round ends if your balance cannot cover another death.":"€10 will be reserved from your demo wallet. The first side to 5 eliminations wins. "+(team==="2v2"?"A €40 pot is split equally between the two winning teammates.":"The winner receives the €20 pot.")+" Leaving early forfeits your stake."}</p><p>WASD to move · Mouse or arrow keys to aim · Click or Space to fire · R to reload. Touch controls are also available.</p>{!canEnter({mode,rate:tiers[tier].rate,team:team==="2v2"?"2v2":"1v1",balance})&&<p className="error-text">Insufficient demo credits. Reset your wallet to continue.</p>}<button className="primary" disabled={!loaded||!canEnter({mode,rate:tiers[tier].rate,team:team==="2v2"?"2v2":"1v1",balance})} onClick={start}>{mode==="duel"?"Reserve €10 & enter":"Enter bot arena"}<ArrowRight size={18}/></button></DialogContent></Dialog>
 <Dialog open={!!result} onOpenChange={open=>{if(!open)setResult(null)}}><DialogContent className="sc-dialog"><DialogTitle>{result?.reason}</DialogTitle><DialogDescription>Match results · Demo credits only</DialogDescription><div className="result-stats"><div><b>{result?.kills} / {result?.deaths}</b><small>KILLS / DEATHS</small></div><div><b>€{result?.balance.toFixed(2)}</b><small>DEMO BALANCE</small></div></div><div className="dialog-actions"><button className="primary" onClick={()=>{setResult(null);setLaunch(true)}}>Play again <ArrowRight size={17}/></button><button className="secondary" onClick={()=>setResult(null)}>Back to lobby</button></div></DialogContent></Dialog>
 </div>
}






