'use client';
import { useEffect, useState } from 'react';
import Arena from './arena';
import {canEnter, type MatchConfig, type Result} from '@/lib/game-rules';
import { Crosshair, ArrowUpRight, ArrowRight, Target, Swords, Zap, Wallet, ShieldCheck, Gamepad2, CircleHelp, Trophy } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
type Mode = 'practice' | 'ffa' | 'duel';
const tiers = [{name:'Beginner',rate:2,desc:'Find your footing',icon:Target},{name:'Contender',rate:5,desc:'Raise the stakes',icon:Zap},{name:'Pro',rate:10,desc:'Every shot matters',icon:Trophy}];
export default function Home(){
 const [mode,setMode]=useState<Mode>('ffa'); const [tier,setTier]=useState(0); const [team,setTeam]=useState('1v1'); const [info,setInfo]=useState(false); const [wallet,setWallet]=useState(false); const [launch,setLaunch]=useState(false);
 const [balance,setBalance]=useState(100);const [game,setGame]=useState<MatchConfig|null>(null);const [result,setResult]=useState<Result|null>(null);const [history,setHistory]=useState<{name:string;delta:number;date:string}[]>([]);const [loaded,setLoaded]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('skillclash-demo-v1')||'null');if(saved&&Number.isFinite(saved.balance)&&saved.balance>=0){setBalance(saved.balance);if(Array.isArray(saved.history))setHistory(saved.history.filter((v:unknown)=>v&&typeof v==='object'&&'delta' in v&&Number.isFinite(v.delta)&&'name' in v&&typeof v.name==='string'&&'date' in v&&typeof v.date==='string').slice(0,10))}}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded){try{localStorage.setItem('skillclash-demo-v1',JSON.stringify({balance,history}))}catch{}}},[balance,history,loaded]);
 function start(){const c:MatchConfig={mode,rate:tiers[tier].rate,team:team==='2v2'?'2v2':'1v1',balance};if(!canEnter(c))return;setLaunch(false);setResult(null);if(mode==='duel'){c.balance-=10;setBalance(c.balance)}setGame(c)}
 function finishMatch(r:Result){if(!game)return;const startBalance=game.balance+(game.mode==='duel'?10:0);setBalance(r.balance);if(r.reason!=='Match cancelled')setHistory(h=>[{name:game.mode==='practice'?'Practice':game.mode==='ffa'?'Cash FFA':game.team+' duel',delta:r.balance-startBalance,date:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})},...h].slice(0,10));setResult({...r,balance:r.balance});setGame(null)}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'configure_match',title:'Configure a SkillClash match',description:'Select a demo mode and open its pre-match review. Does not spend credits or start gameplay.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['practice','ffa','duel']},tier:{type:'integer',minimum:0,maximum:2},team:{type:'string',enum:['1v1','2v2']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const v=input as {mode:Mode;tier?:number;team?:string};if(!v||!['practice','ffa','duel'].includes(v.mode)||(v.tier!==undefined&&(!Number.isInteger(v.tier)||v.tier<0||v.tier>2))||(v.team!==undefined&&!['1v1','2v2'].includes(v.team)))throw new Error('Invalid match configuration');if(game)throw new Error('Leave the current match first');setMode(v.mode);if(v.tier!==undefined)setTier(v.tier);if(v.team)setTeam(v.team);setLaunch(true);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {mode:v.mode,status:'ready_for_review',demo:true}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[game]);
 if(game)return <Arena config={game} onFinish={finishMatch}/>;
 return <div className="site-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="SkillClash home"><Crosshair/><span>SKILL<span>CLASH</span></span></a><div className="top-nav"><span className="nav-active"><Gamepad2 size={17}/> Play</span><button onClick={()=>setInfo(true)}><CircleHelp size={17}/> How it works</button></div><div className="account"><span className="demo-badge">DEMO</span><button className="wallet-button" onClick={()=>setWallet(true)}><Wallet size={17}/><b>€{balance.toFixed(2)}</b><span>+</span></button><div className="avatar">P1</div></div></header>
 <main className="main"><div className="page-heading"><div><div className="eyebrow">THE ARENA IS YOURS</div><h1>LET YOUR AIM TALK<span>.</span></h1></div><div className="server-status"><span/> Bot arena <i/> Prototype</div></div>
 <section className="feature"><div className="feature-art"/><div className="feature-shade"/><div className="feature-copy"><div className="feature-label"><span/> SKILLCLASH ORIGINAL</div><h2>GOOD AIM.<br/>HIGHER STAKES.</h2><p>Warm up. Find your level. Make every shot count.</p><button className="primary" onClick={()=>{setMode('practice');setLaunch(true)}}>Enter practice <ArrowUpRight size={19}/></button></div><div className="map-caption"><span>01 / THE FOUNDRY</span><small>INDUSTRIAL · CLOSE QUARTERS</small></div><div className="feature-number">SC / 001</div></section>
 <div className="section-heading"><h2>CHOOSE YOUR BATTLEGROUND</h2><span>Three ways to play. One way to win.</span></div>
 <div className="mode-grid">{([{id:'practice',title:'Practice',tag:'NO STAKES. ALL SKILL.',desc:'Learn the map. Dial in your aim. Get ready for the real thing.',icon:Crosshair,foot:'Free to play',meta:'FFA · 10 players'}, {id:'ffa',title:'Cash FFA',tag:'EVERY ELIMINATION COUNTS.',desc:'Everyone is a target. Earn on every kill. Lose on every death.',icon:Zap,foot:'From €2 / kill',meta:'FFA · 10 players'}, {id:'duel',title:'Duels',tag:'SETTLE IT IN THE ARENA.',desc:'Go head-to-head or bring a teammate. The winning side takes the pot.',icon:Swords,foot:'€10 / player',meta:'1v1 or 2v2'}] as const).map(m=><button key={m.id} className={'mode-card '+(mode===m.id?'selected':'')} onClick={()=>setMode(m.id)} aria-pressed={mode===m.id}><div className="card-top"><m.icon size={29}/><span className="mode-dot">{mode===m.id?'SELECTED':'0'+(['practice','ffa','duel'].indexOf(m.id)+1)}</span></div><div className="eyebrow">{m.tag}</div><h3>{m.title}</h3><p>{m.desc}</p><div className="card-bottom"><strong>{m.foot}</strong><span>{m.meta}</span><ArrowUpRight size={18}/></div></button>)}</div>
 <section className="match-panel"><div className="match-heading"><div><span className="eyebrow">{mode==='ffa'?'PICK YOUR LEVEL':mode==='duel'?'PICK YOUR FORMAT':'BUILD YOUR CONFIDENCE'}</span><h2>{mode==='ffa'?'Small stakes. Big potential.':mode==='duel'?'Your team. Your challenge.':'Your next great shot starts here.'}</h2></div><span className="pill"><ShieldCheck size={15}/> Demo credits only</span></div>
 {mode==='ffa'?<div className="tier-grid">{tiers.map((t,i)=><button className={'tier '+(tier===i?'active':'')} key={t.name} onClick={()=>setTier(i)} aria-pressed={tier===i}><t.icon size={24}/><div><b>{t.name}</b><small>{t.desc}</small></div><div className="tier-rate">€{t.rate}<small>per kill / death</small></div><span className="radio-dot"/></button>)}</div>:mode==='duel'?<Tabs value={team} onValueChange={v=>setTeam(String(v))}><TabsList className="format-tabs"><TabsTrigger value="1v1">1v1 · Solo duel</TabsTrigger><TabsTrigger value="2v2">2v2 · Team duel</TabsTrigger></TabsList></Tabs>:<p className="practice-description">Explore The Foundry in a 10-player FFA format. Instant respawns, no entry cost, and no effect on your balance.</p>}
 <div className="match-bottom"><div><span className="terms-main">{mode==='ffa'?<><b className="positive">+€{tiers[tier].rate} per kill</b><span className="separator">/</span><b>−€{tiers[tier].rate} per death</b></>:mode==='duel'?<><b>€10 per player</b><span className="separator">/</span><b className="positive">€{team==='1v1'?20:40} total pot</b></>:<b className="positive">Free entry. Unlimited practice.</b>}</span><small>{mode==='duel'?(team==='1v1'?'First to 5 eliminations wins the €20 pot.':'First team to 5 wins. €40 split equally between the two winners.'):'10-player format · 3-minute rounds · The Foundry'}</small></div><button className="primary" onClick={()=>setLaunch(true)}>{mode==='practice'?'Start practice':mode==='ffa'?'Play '+tiers[tier].name:'Play '+team+' duel'}<ArrowRight size={18}/></button></div>
 </section><div className="demo-note"><ShieldCheck size={18}/><p><b>Arena preview</b> · Play against bots with demo credits. Real-player matchmaking, deposits, and withdrawals are not connected.</p></div>
 <footer><span className="footer-brand">SKILLCLASH</span><span>Built for the thrill of the match.</span><button onClick={()=>setInfo(true)}>Game rules <ArrowUpRight size={14}/></button></footer></main>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent className="sc-dialog"><DialogTitle>Know the rules</DialogTitle><DialogDescription>Three modes, one arena. This prototype uses bots and demo credits.</DialogDescription><div className="rule"><Crosshair/><div><h3>Practice</h3><p>Free FFA. Warm up with nine bots. Kills and deaths do not change your balance.</p></div></div><div className="rule"><Zap/><div><h3>Cash FFA</h3><p>Beginner: €2, Contender: €5, Pro: €10 per kill or death. A kill credits your balance; a death deducts the same amount. A round ends if you cannot cover another death.</p></div></div><div className="rule"><Swords/><div><h3>Duels</h3><p>Each player puts in €10. First side to 5 wins. In 1v1 the winner receives €20. In 2v2 the €40 pot is split equally between the winning teammates. Leaving early forfeits the stake.</p></div></div></DialogContent></Dialog>
 <Dialog open={wallet} onOpenChange={setWallet}><DialogContent className="sc-dialog"><DialogTitle>Your demo wallet</DialogTitle><DialogDescription>Demo credits have no cash value and cannot be withdrawn.</DialogDescription><div className="wallet-amount">€{balance.toFixed(2)}</div><p>Your balance is saved on this device. Payments are not connected in this preview.</p><button className="secondary" onClick={()=>{setBalance(100);setHistory([])}}>Reset demo wallet to €100</button><div className="wallet-history">{history.length===0?<p>No matches yet. Your results will appear here.</p>:history.map((h,i)=><div key={i}><span>{h.name}<small>{h.date}</small></span><b>{h.delta>=0?"+":"−"}€{Math.abs(h.delta).toFixed(2)}</b></div>)}</div></DialogContent></Dialog>
 <Dialog open={launch} onOpenChange={setLaunch}><DialogContent className="sc-dialog"><DialogTitle>{mode==='practice'?'Practice':mode==='ffa'?tiers[tier].name+' FFA':team+' duel'}</DialogTitle><DialogDescription>The Foundry · Bot arena · Demo credits</DialogDescription><p>{mode==="practice"?"Free entry. Warm up against nine bots in a three-minute round.":mode==="ffa"?"Earn €"+tiers[tier].rate+" per kill and lose €"+tiers[tier].rate+" per death. The round ends if your balance cannot cover another death.":"€10 will be reserved from your demo wallet. The first side to 5 eliminations wins. "+(team==="2v2"?"A €40 pot is split equally between the two winning teammates.":"The winner receives the €20 pot.")+" Leaving early forfeits your stake."}</p><p>WASD to move · Mouse or arrow keys to aim · Click or Space to fire · R to reload. Touch controls are also available.</p>{!canEnter({mode,rate:tiers[tier].rate,team:team==="2v2"?"2v2":"1v1",balance})&&<p className="error-text">Insufficient demo credits. Reset your wallet to continue.</p>}<button className="primary" disabled={!loaded||!canEnter({mode,rate:tiers[tier].rate,team:team==="2v2"?"2v2":"1v1",balance})} onClick={start}>{mode==="duel"?"Reserve €10 & enter":"Enter bot arena"}<ArrowRight size={18}/></button></DialogContent></Dialog>
 <Dialog open={!!result} onOpenChange={open=>{if(!open)setResult(null)}}><DialogContent className="sc-dialog"><DialogTitle>{result?.reason}</DialogTitle><DialogDescription>Match results · Demo credits only</DialogDescription><div className="result-stats"><div><b>{result?.kills} / {result?.deaths}</b><small>KILLS / DEATHS</small></div><div><b>€{result?.balance.toFixed(2)}</b><small>DEMO BALANCE</small></div></div><div className="dialog-actions"><button className="primary" onClick={()=>{setResult(null);setLaunch(true)}}>Play again <ArrowRight size={17}/></button><button className="secondary" onClick={()=>setResult(null)}>Back to lobby</button></div></DialogContent></Dialog>
 </div>
}



