'use client';
import CosmeticShop from './cosmetic-shop';
import {useEffect,useState} from 'react';
import {Crosshair,Swords,Users,ShieldCheck,ArrowRight,Check,Trophy,Settings2,Flag} from 'lucide-react';
import SiteHeader from './site-header';
import {useAccount,accountApi,type AccountData} from './account-context';
import {rankNames,demoRating} from '@/lib/catalog';
import './platform.css';

type Platform={party:null|{id:string;owner_id:string;name:string;members:{id:string;player_id:string;name:string;handle:string;status:string}[]};invites:{id:string;name:string}[];challenges:{id:string;sender_id:string;receiver_id:string;sender_name:string;receiver_name:string;rules:string;status:string;expires_at:number}[];inventory:{sku:string;equipped:number}[];reports:{id:string;category:string;details:string;status:string;created_at:number}[];ratings:{mode:string;matches:number;wins:number;kills:number;deaths:number;rating:number;rank:string}[]};
const titles={party:['YOUR PARTY','Invite your people and plan your next match.'],shop:['THE ARMORY','Express your style. Every weapon keeps the same competitive stats.'],inventory:['YOUR LOADOUT','Owned cosmetics, ready for your next match.'],ranked:['YOUR COMPETITIVE RECORD','Separate Duel and Arena progress, with clear placement rules.'],settings:['YOUR SETUP','Tune your controls, sound and graphics.'],support:['REPORTS & SUPPORT','Keep a record of problems and disputed demo matches.']};
export type PlatformSection=keyof typeof titles;
export default function PlatformPage({section,embedded=false}:{section:PlatformSection;embedded?:boolean}){
 const {data,loading,error,update,refresh}=useAccount();const [platform,setPlatform]=useState<Platform|null>(null),[failure,setFailure]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [handle,setHandle]=useState(''),[partyName,setPartyName]=useState('My squad');
 const [category,setCategory]=useState('bug'),[details,setDetails]=useState(''),[matchId,setMatchId]=useState('');
 const [preferences,setPreferences]=useState({sensitivity:1,fov:80,quality:'high',muted:false});
 async function load(){try{setPlatform(await accountApi<Platform>(undefined,'?action=platform'));setFailure('');}catch(e){setFailure((e as Error).message);}}
 useEffect(()=>{if(data)void load();},[data?.player.id]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setHandle(p.get('opponent')??'');try{const saved=JSON.parse(localStorage.getItem('skillclash-controls')??'{}');setPreferences({sensitivity:Number(saved.sensitivity)||1,fov:Number(saved.fov)||80,quality:saved.quality==='low'?'low':'high',muted:saved.muted===true});}catch{}},[]);
 async function act(body:Record<string,unknown>,success:string){if(busy)return;setBusy(true);setFailure('');setMessage('');try{const response=await accountApi<AccountData&{platform:Platform}>(body);update(response);setPlatform(response.platform);setMessage(success);}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 const owned=new Set(platform?.inventory.map(i=>i.sku)??[]),equipped=platform?.inventory.find(i=>i.equipped)?.sku;
 const heading=titles[section];
 return <div className={embedded?'party-integrated':'site-shell'} id={embedded?'party':undefined}>{!embedded&&<SiteHeader/>}<div className={embedded?'':'main account-main platform-main'}>{!embedded&&<div className="page-heading"><div><div className="eyebrow"><span className="orange-line"/>FRAGSTAKE / {section.toUpperCase()}</div><h1>{heading[0]}<span>.</span></h1><p className="account-subtitle">{heading[1]}</p></div><span className="demo-badge">DEMO PLATFORM</span></div>}
 {(failure||error)&&<div className="account-notice error" role="alert"><p>{failure||error}</p><button className="secondary" onClick={()=>{void refresh();void load();}}>Retry</button><a className="secondary" href="/signin">Sign in</a></div>}{message&&<div className="account-notice success" role="status"><Check size={18}/>{message}</div>}
 {section==='party'&&<div className="platform-two"><section className="account-panel"><Users size={34}/><h2>{platform?.party?.name??'CREATE YOUR PARTY'}</h2>{platform?.party?<><p>{platform.party.members.filter(m=>m.status==='joined').length} joined · Up to 6 members and invitations</p>{platform.party.members.map(m=><div className="platform-list-row" key={m.id}><div><b>{m.name}</b><p>@{m.handle}</p></div><span className="table-badge">{m.player_id===platform.party?.owner_id?'Leader':m.status}</span></div>)}{platform.party.owner_id===data?.player.id&&<form className="platform-fields" onSubmit={e=>{e.preventDefault();void act({action:'party_invite',handle},'Party invitation sent.');}}><label>Invite by player handle<input required value={handle} onChange={e=>setHandle(e.target.value.replace(/^@/,''))}/></label><button className="primary" disabled={busy}>Invite player</button></form>}<button className="secondary" disabled={busy} onClick={()=>void act({action:'party_leave'},'You left the party.')}>{platform.party.owner_id===data?.player.id?'Disband party':'Leave party'}</button></>:<form className="platform-fields" onSubmit={e=>{e.preventDefault();void act({action:'party_create',name:partyName},'Party created. Invite a registered friend.');}}><label>Party name<input minLength={2} maxLength={40} required value={partyName} onChange={e=>setPartyName(e.target.value)}/></label><button className="primary" disabled={busy||!data}>Create party <Users size={17}/></button></form>}<p className="platform-note">Party membership and invitations are saved. Joining the same live game, 3v3 and spectating require the multiplayer server.</p></section><section className="account-panel"><h2>PARTY INVITATIONS</h2>{platform?.invites.length?platform.invites.map(i=><div className="platform-list-row" key={i.id}><b>{i.name}</b><button className="primary compact" disabled={busy} onClick={()=>void act({action:'party_accept',id:i.id},'Joined the party.')}>Join</button><button className="secondary compact" disabled={busy} onClick={()=>void act({action:'party_decline',id:i.id},'Invitation declined.')}>Decline</button></div>):<p className="platform-empty">Your party invitations will appear here.</p>}<a className="secondary" href="/friends">Find friends <ArrowRight size={16}/></a></section></div>}
 {(section==='shop'||section==='inventory')&&<CosmeticShop inventory={section==='inventory'} owned={owned} equipped={equipped} busy={busy} signedIn={!!data} act={act}/>}
 {section==='ranked'&&<><div className="account-notice"><Trophy size={23}/><p><b>DEMO RATINGS · UNVERIFIED BOT MATCHES</b><br/>These progress ratings are separate for Duel and Arena. They are not a human ELO rating or real-money eligibility.</p></div><div className="platform-two">{['duel','ffa'].map(mode=>{const row=platform?.ratings.find(r=>r.mode===mode),rating=row??{matches:0,wins:0,kills:0,deaths:0,...demoRating(0,0)};return <section className="account-panel rank-card" key={mode}><span className="eyebrow">{mode==='duel'?'DUEL':'ARENA'} RATING</span><Trophy size={48}/><h2>{rating.matches<5?'PLACEMENT':rating.rank.toUpperCase()}</h2><strong>{rating.rating}</strong><p>{Math.min(5,rating.matches)} / 5 placement matches completed</p><progress value={Math.min(5,rating.matches)} max={5}/><dl><div><dt>Wins / matches</dt><dd>{rating.wins} / {rating.matches}</dd></div><div><dt>Win rate</dt><dd>{rating.matches?Math.round(rating.wins/rating.matches*100):0}%</dd></div><div><dt>K / D</dt><dd>{(rating.kills/Math.max(1,rating.deaths)).toFixed(2)}</dd></div></dl></section>;})}</div><section className="account-panel"><h2>THE RANK LADDER</h2><div className="rank-ladder">{rankNames.map((name,i)=><div key={name}><Trophy size={20}/><b>{name}</b><small>{i===0?'Under 1,100':(900+i*200).toLocaleString('en-GB')+'+'}</small></div>)}</div><p className="platform-note">Demo rating starts at 1,000: +25 per win, −15 per other completed result. Stakes do not multiply progress. Human skill matching needs authoritative multiplayer results.</p><a className="primary" href="/leaderboard">View leaderboards <ArrowRight size={16}/></a></section></>}
 {section==='settings'&&<section className="account-panel settings-panel"><Settings2 size={32}/><h2>CONTROLS & PERFORMANCE</h2><form className="platform-fields" onSubmit={e=>{e.preventDefault();localStorage.setItem('skillclash-controls',JSON.stringify(preferences));setMessage('Settings saved on this device. They apply to your next match.');}}><label>Mouse sensitivity · {preferences.sensitivity.toFixed(1)}<input type="range" min="0.3" max="2.5" step="0.1" value={preferences.sensitivity} onChange={e=>setPreferences(p=>({...p,sensitivity:Number(e.target.value)}))}/></label><label>Field of view · {preferences.fov}°<input type="range" min="65" max="100" value={preferences.fov} onChange={e=>setPreferences(p=>({...p,fov:Number(e.target.value)}))}/></label><label>Graphics<select value={preferences.quality} onChange={e=>setPreferences(p=>({...p,quality:e.target.value}))}><option value="high">High — full atmosphere and lighting</option><option value="low">Performance — reduced effects</option></select></label><label className="checkbox-label"><input type="checkbox" checked={preferences.muted} onChange={e=>setPreferences(p=>({...p,muted:e.target.checked}))}/>Mute game sound</label><button className="primary">Save settings <Check size={17}/></button></form><dl><div><dt>Move / look</dt><dd>WASD / mouse</dd></div><div><dt>Sprint / crouch / jump</dt><dd>Shift / Ctrl / Space</dd></div><div><dt>Slide</dt><dd>C</dd></div><div><dt>Fire / aim / reload</dt><dd>Left click / right click / R</dd></div><div><dt>Weapons / pause</dt><dd>1–6 / Esc</dd></div></dl><a className="secondary" href="/profile">Edit player profile</a></section>}
 {section==='support'&&<div className="platform-two"><section className="account-panel"><Flag size={32}/><h2>SUBMIT A REPORT</h2><form className="platform-fields" onSubmit={e=>{e.preventDefault();void act({action:'report_create',category,details,matchId},'Report recorded in your account.');}}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="bug">Game or page problem</option><option value="cheating">Suspicious play</option><option value="payment">Demo wallet / match result</option><option value="other">Other</option></select></label><label>Related match<select value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">No specific match</option>{data?.matches.map(m=><option value={m.id} key={m.id}>{m.mode} · {new Date(m.started_at).toLocaleString()}</option>)}</select></label><label>What happened?<textarea required minLength={10} maxLength={2000} rows={6} value={details} onChange={e=>setDetails(e.target.value)}/></label><button className="primary" disabled={busy||!data}>Save report</button></form><p className="platform-note">Reports are stored for review. This demo has no staffed support queue, automated anti-cheat verdicts or real payouts.</p></section><section className="account-panel"><h2>YOUR REPORTS</h2>{platform?.reports.length?platform.reports.map(r=><article className="platform-list-row" key={r.id}><div><b>{r.category.toUpperCase()}</b><p>{r.details}</p><small>{new Date(r.created_at).toLocaleString()}</small></div><span className="table-badge">{r.status}</span></article>):<p className="platform-empty">No reports filed.</p>}</section></div>}
 {loading&&section!=='settings'&&<p className="platform-note">Connecting your saved account… You can still browse match rules and the catalog.</p>}
 {!embedded&&<footer><span className="footer-brand">FRAGSTAKE</span><a href="/support">Reports & support</a><span>DEMO CREDITS · BOT GAMEPLAY</span></footer>}</div></div>;
}
