'use client';
import {useEffect,useState} from 'react';
import SiteHeader from './site-header';
import {useAccount} from './account-context';
import {getMap} from '@/lib/fps/maps';
type Records={leaders:{handle:string;name:string;matches:number;kills:number;deaths:number;wins:number}[];recent:{id:string;mode:string;map_id:string;kills:number;deaths:number;won:number;completed:number;finished_at:number}[];stats:{matches:number;kills:number;deaths:number;wins:number}|null};
export default function PlayerRecords({history=false}:{history?:boolean}){
 const {data}=useAccount(),[records,setRecords]=useState<Records|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const response=await fetch('/api/records',{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error('Records are unavailable. Please retry.');setRecords(await response.json());setError('')}catch(e){setError(e instanceof Error?e.message:'Records unavailable.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[data?.player.id]);
 return <div className="site-shell"><SiteHeader/><main className="main account-main"><div className="page-heading"><div><span className="eyebrow">SERVER-RECORDED MATCHES</span><h1>{history?'HISTORY & STATS':'LEADERBOARD'}<span>.</span></h1></div><button className="secondary compact" onClick={()=>void load()} disabled={loading}>Refresh</button></div>{error&&<p className="error-text" role="alert">{error}</p>}{loading?<p role="status">Loading match records…</p>:history&&!data?<div className="real-empty"><h2>Keep your match record.</h2><p>Sign in before playing to save your results across devices.</p><a className="primary" href="/signin">Sign in</a></div>:history?<>{records?.stats&&<div className="real-stats">{Object.entries(records.stats).filter(([key])=>['matches','kills','deaths','wins'].includes(key)).map(([key,value])=><div key={key}><strong>{value}</strong>{key.toUpperCase()}</div>)}</div>}{records?.recent.length?<table className="real-record"><thead><tr><th>Match</th><th>K / D</th><th>Result</th></tr></thead><tbody>{records.recent.map(row=><tr key={row.id}><td>{getMap(row.map_id).name}<small style={{display:'block'}}>{row.mode.toUpperCase()} · {new Date(row.finished_at).toLocaleDateString()}</small></td><td>{row.kills} / {row.deaths}</td><td>{!row.completed?'Left early':row.won?'Won':'Completed'}</td></tr>)}</tbody></table>:<div className="real-empty"><h2>Your first match starts here.</h2><p>Completed player matches will appear here.</p><a className="primary" href="/play">Find a match</a></div>}</>:records?.leaders.length?<table className="real-record"><thead><tr><th>Rank</th><th>Player</th><th>Wins</th><th>Kills</th></tr></thead><tbody>{records.leaders.map((row,i)=><tr key={row.handle}><td>{i+1}</td><td>{row.name}<small style={{display:'block'}}>@{row.handle}</small></td><td>{row.wins}</td><td>{row.kills}</td></tr>)}</tbody></table>:<div className="real-empty"><h2>The first place is open.</h2><p>Rankings appear after signed-in players complete live matches. Sorted by wins, then kills.</p><a className="primary" href="/play">Play now</a></div>}</main></div>
}
