'use client';
const Link = 'a';
import './platform.css';
import './lobby-refresh.css';
import {usePathname} from 'next/navigation';
import {Crosshair,Gamepad2,Wallet,Users,Trophy,History,UserRound,Swords,ShoppingBag,Settings2} from 'lucide-react';
import {useAccount,euro} from './account-context';
export function PlayerAvatar({name,color='orange',large=false}:{name:string;color?:string;large?:boolean}){return <span className={'player-avatar color-'+color+(large?' large':'')}>{name.slice(0,2).toUpperCase()}</span>}
export default function SiteHeader(){const {data}=useAccount();const path=usePathname();return <header className="topbar community-header"><Link className="brand" href="/" aria-label="SkillClash lobby"><span className="brand-symbol"><Crosshair/></span><span>SKILL<span>CLASH</span><small>COMPETITIVE ARENA</small></span></Link><nav className="top-nav community-nav" aria-label="Main navigation">{[{path:'/',name:'Play',icon:Gamepad2},{path:'/shop',name:'Shop',icon:ShoppingBag},{path:'/wallet',name:'Wallet',icon:Wallet},{path:'/friends',name:'Friends',icon:Users},{path:'/leaderboard',name:'Leaderboard',icon:Trophy},{path:'/history',name:'History & Stats',icon:History}].map(n=><Link key={n.path} className={path===n.path?'nav-active':''} href={n.path}><n.icon size={17}/><span>{n.name}</span>{n.path==='/friends'&&!!data?.pending&&<b className="request-count">{data.pending}</b>}</Link>)}</nav><div className="account"><a href="/settings" className="icon-button" aria-label="Settings"><Settings2 size={19}/></a><Link className="wallet-button" href="/wallet"><span className="wallet-label">DEMO BALANCE</span><b>{data?euro(data.player.balance):'—'}</b><span className="wallet-plus">+</span></Link><Link href="/profile" aria-label="Your profile" className={path==='/profile'?'profile-link active':'profile-link'}>{data?<PlayerAvatar name={data.player.name} color={data.player.color}/>:<UserRound size={22}/>}</Link></div></header>}
