export class InputError extends Error { status:number; constructor(message:string,status=400){super(message);this.status=status} }
export function textValue(value:unknown,label:string,min:number,max:number){if(typeof value!=='string'||value.trim().length<min||value.trim().length>max)throw new InputError(`${label} must be ${min}–${max} characters.`);return value.trim();}
export function countValue(value:unknown,label:string,max=1000){if(typeof value!=='number'||!Number.isInteger(value)||value<0||value>max)throw new InputError(`Invalid ${label}.`);return value;}
export function validateProfile(v:Record<string,unknown>){const handle=textValue(v.handle,'Handle',3,20).toLowerCase();if(!/^[a-z0-9_]+$/.test(handle))throw new InputError('Use letters, numbers and underscores in your handle.');const name=textValue(v.name,'Display name',2,32),bio=textValue(v.bio??'','Bio',0,160),color=String(v.color);if(!['orange','blue','purple','green','pink'].includes(color))throw new InputError('Choose an avatar color.');return {handle,name,bio,color};}
export function matchSetup(v:Record<string,unknown>){const mode=String(v.mode),rate=Number(v.rate),team=String(v.team),mapId=String(v.mapId??'citadel');if(!['practice','ffa','duel'].includes(mode)||![1,2,5,10].includes(rate)||!['1v1','2v2'].includes(team)||!['citadel','depot','underpass','foundry','relay','drydock'].includes(mapId))throw new InputError('Invalid match settings.');const stake=Number(v.stake??10),target=Number(v.target??5),bestOf=Number(v.bestOf??1),weaponRule=v.weaponRule==='pistol'?'standard':String(v.weaponRule??'standard'),entry=mode==='ffa'?Number(v.entry??0):0;if(!Number.isInteger(stake)||stake<5||stake>100||![5,10].includes(target)||![1,3].includes(bestOf)||!['standard','rifle','sniper','pistol','headshots'].includes(weaponRule)||!Number.isFinite(entry)||entry<0||(entry!==0&&entry!==rate*10))throw new InputError('Invalid competition rules.');return {mode,rate,team,mapId,stake,target,bestOf,weaponRule,entry};}
export function settlement(match:{mode:string;rate:number;stake?:number;target?:number;best_of?:number;entry?:number},v:Record<string,unknown>,balance:number){
 const limit=match.best_of===3?2:(match.target??5),stake=match.stake??1000,entry=match.entry??0;
 const kills=countValue(v.kills,'kills'),deaths=countValue(v.deaths,'deaths'),score=countValue(v.score,'team score',limit),enemyScore=countValue(v.enemyScore,'opponent score',limit),headshots=countValue(v.headshots??0,'headshots',kills),maxStreak=countValue(v.maxStreak??0,'kill streak',kills);
 const ending=String(v.ending);if(!['complete','leave','cancel','cashout'].includes(ending)||(ending==='cashout'&&match.mode!=='ffa'))throw new InputError('Invalid match ending.');
 if(ending==='cancel'&&(kills||deaths||score||enemyScore))throw new InputError('A played match cannot be cancelled.');if(match.mode==='duel'&&score===limit&&enemyScore===limit)throw new InputError('Both teams cannot win.');
 const won=['complete','cashout'].includes(ending)&&(match.mode==='duel'?score>enemyScore:kills>deaths),draw=ending==='complete'&&score===enemyScore;
 let delta=0,reserved=0;
 if(match.mode==='duel'){reserved=stake;delta=ending==='cancel'?stake:won?stake*2:draw?stake:0;}
 if(match.mode==='ffa'){reserved=entry;delta=entry>0?(ending==='cancel'?entry:ending==='leave'?0:Math.max(0,entry+(kills-deaths)*match.rate*100)):Math.max(-balance,(kills-deaths)*match.rate*100);}
 const net=delta-reserved,reason=ending==='cancel'?'Match cancelled':ending==='cashout'?'Arena cash-out':ending==='leave'?(match.mode==='duel'?'Duel forfeited':entry>0?'Arena session forfeited':'Left the arena'):match.mode==='duel'?(won?'Duel won':draw?'Draw — stake returned':'Duel lost'):'Round complete';
 return {kills,deaths,score,enemyScore,headshots,maxStreak,won,delta,net,reason,status:ending==='cancel'?'cancelled':'completed'};
}

