import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const players = sqliteTable('players', {
 id:text('id').primaryKey(), handle:text('handle').notNull().unique(), name:text('name').notNull(), bio:text('bio').notNull().default(''), color:text('color').notNull().default('orange'), balance:integer('balance').notNull().default(10000), createdAt:integer('created_at').notNull(), lastSeen:integer('last_seen').notNull()
},t=>[check('balance_nonnegative',sql`${t.balance} >= 0`)]);
export const matches=sqliteTable('matches',{
 id:text('id').primaryKey(), playerId:text('player_id').notNull().references(()=>players.id), mode:text('mode').notNull(), rate:integer('rate').notNull(), team:text('team').notNull(), mapId:text('map_id').notNull().default('foundry'), stake:integer('stake').notNull().default(1000), target:integer('target').notNull().default(5), bestOf:integer('best_of').notNull().default(1), weaponRule:text('weapon_rule').notNull().default('standard'), entry:integer('entry').notNull().default(0), headshots:integer('headshots').notNull().default(0), maxStreak:integer('max_streak').notNull().default(0), status:text('status').notNull().default('active'), kills:integer('kills').notNull().default(0), deaths:integer('deaths').notNull().default(0), score:integer('score').notNull().default(0), enemyScore:integer('enemy_score').notNull().default(0), won:integer('won').notNull().default(0), delta:integer('delta').notNull().default(0), reason:text('reason').notNull().default(''), startedAt:integer('started_at').notNull(), finishedAt:integer('finished_at')
},t=>[index('idx_matches_player_time').on(t.playerId,t.startedAt),index('idx_matches_status_time').on(t.status,t.finishedAt),uniqueIndex('idx_one_active_match').on(t.playerId).where(sql`${t.status} = 'active'`)]);
export const transactions=sqliteTable('transactions',{
 id:text('id').primaryKey(), playerId:text('player_id').notNull().references(()=>players.id), kind:text('kind').notNull(), amount:integer('amount').notNull(), label:text('label').notNull(), matchId:text('match_id').references(()=>matches.id), createdAt:integer('created_at').notNull()
},t=>[index('idx_transactions_player_time').on(t.playerId,t.createdAt)]);
export const friendships=sqliteTable('friendships',{
 id:text('id').primaryKey(), senderId:text('sender_id').notNull().references(()=>players.id), receiverId:text('receiver_id').notNull().references(()=>players.id), status:text('status').notNull().default('pending'), createdAt:integer('created_at').notNull()
},t=>[index('idx_friends_sender').on(t.senderId,t.status),index('idx_friends_receiver').on(t.receiverId,t.status),check('no_self_friend',sql`${t.senderId} != ${t.receiverId}`)]);

export const parties=sqliteTable('parties',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>players.id),name:text('name').notNull(),createdAt:integer('created_at').notNull()});
export const partyMembers=sqliteTable('party_members',{id:text('id').primaryKey(),partyId:text('party_id').notNull().references(()=>parties.id),playerId:text('player_id').notNull().references(()=>players.id),status:text('status').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('idx_party_player').on(t.partyId,t.playerId),uniqueIndex('idx_one_joined_party').on(t.playerId).where(sql`${t.status} = 'joined'`)]);
export const challenges=sqliteTable('challenges',{id:text('id').primaryKey(),senderId:text('sender_id').notNull().references(()=>players.id),receiverId:text('receiver_id').notNull().references(()=>players.id),rules:text('rules').notNull(),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_challenge_receiver').on(t.receiverId,t.status),index('idx_challenge_sender').on(t.senderId,t.status)]);
export const inventory=sqliteTable('inventory',{id:text('id').primaryKey(),playerId:text('player_id').notNull().references(()=>players.id),sku:text('sku').notNull(),equipped:integer('equipped').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('idx_inventory_player_sku').on(t.playerId,t.sku)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),playerId:text('player_id').notNull().references(()=>players.id),matchId:text('match_id'),category:text('category').notNull(),details:text('details').notNull(),status:text('status').notNull().default('open'),createdAt:integer('created_at').notNull()},t=>[index('idx_reports_player').on(t.playerId,t.createdAt)]);

export const duelLobbies=sqliteTable('duel_lobbies',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>players.id),rules:text('rules').notNull(),status:text('status').notNull().default('open'),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_open_lobbies').on(t.status,t.createdAt),uniqueIndex('idx_one_hosted_lobby').on(t.ownerId).where(sql`${t.status} = 'open'`)]);
export const duelLobbyMembers=sqliteTable('duel_lobby_members',{id:text('id').primaryKey(),lobbyId:text('lobby_id').notNull().references(()=>duelLobbies.id),playerId:text('player_id').notNull().references(()=>players.id),ready:integer('ready').notNull().default(0),joinedAt:integer('joined_at').notNull()},t=>[uniqueIndex('idx_lobby_member').on(t.lobbyId,t.playerId)]);
