import {InputError,validateProfile,matchSetup,settlement,textValue} from '../lib/account-rules.ts';
export type Player={id:string;handle:string;name:string;bio:string;color:string;balance:number;created_at:number;last_seen:number};
export type MatchRow={id:string;player_id:string;mode:string;rate:number;team:string;status:string;kills:number;deaths:number;score:number;enemy_score:number;won:number;delta:number;reason:string;started_at:number;finished_at:number|null};
const pub='p.id,p.handle,p.name,p.bio,p.color,p.created_at,p.last_seen';
export async function ensurePlayer(db:D1Database,id:string){const now=Date.now();let player=await db.prepare('SELECT * FROM players WHERE id=?').bind(id).first<Player>();if(!player){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(id)))).map(n=>n.toString(16).padStart(2,'0')).join('').slice(0,10);await db.batch([db.prepare('INSERT OR IGNORE INTO players (id,handle,name,created_at,last_seen) VALUES (?,?,?,?,?)').bind(id,'player_'+hash,'Player '+hash.slice(0,4).toUpperCase(),now,now),db.prepare("INSERT OR IGNORE INTO transactions (id,player_id,kind,amount,label,created_at) VALUES (?,?,'welcome',10000,'Welcome demo credits',?)").bind('welcome:'+id,id,now)]);player=await db.prepare('SELECT * FROM players WHERE id=?').bind(id).first<Player>()}else if(now-player.last_seen>30000){await db.prepare('UPDATE players SET last_seen=? WHERE id=?').bind(now,id).run()}if(!player)throw new Error('Could not create player.');return player;}
export async function stats(db:D1Database,id:string){return db.prepare("SELECT COUNT(*) AS matches, COALESCE(SUM(kills),0) AS kills, COALESCE(SUM(deaths),0) AS deaths, COALESCE(SUM(won),0) AS wins, COALESCE(SUM(delta),0) AS net FROM matches WHERE player_id=? AND status='completed'").bind(id).first();}
export async function state(db:D1Database,id:string){const [player,summary,ledger,recent,active,pending]=await Promise.all([db.prepare('SELECT * FROM players WHERE id=?').bind(id).first(),stats(db,id),db.prepare('SELECT * FROM transactions WHERE player_id=? ORDER BY created_at DESC,id DESC LIMIT 50').bind(id).all(),db.prepare("SELECT * FROM matches WHERE player_id=? AND status!='active' ORDER BY started_at DESC LIMIT 50").bind(id).all(),db.prepare("SELECT * FROM matches WHERE player_id=? AND status='active'").bind(id).first(),db.prepare("SELECT COUNT(*) AS count FROM friendships WHERE receiver_id=? AND status='pending'").bind(id).first<{count:number}>()]);return {player,stats:summary,transactions:ledger.results,matches:recent.results,active,pending:pending?.count||0};}
export async function getData(db:D1Database,id:string,url:URL){const action=url.searchParams.get('action')||'state';if(action==='state')return state(db,id);
 if(action==='friends'){const rows=await db.prepare(`SELECT f.id AS friendship_id,f.sender_id,f.receiver_id,f.status,f.created_at AS requested_at,${pub} FROM friendships f JOIN players p ON p.id=CASE WHEN f.sender_id=? THEN f.receiver_id ELSE f.sender_id END WHERE f.sender_id=? OR f.receiver_id=? ORDER BY f.created_at DESC`).bind(id,id,id).all();return {friends:rows.results};}
 if(action==='search'){const q=(url.searchParams.get('q')||'').trim().toLowerCase();if(q.length<2)return {players:[]};if(q.length>32)throw new InputError('Search is too long.');const like='%'+q.replace(/[!%_]/g,'!$&')+'%';const rows=await db.prepare(`SELECT ${pub},f.id AS friendship_id,f.status AS friendship_status,f.sender_id FROM players p LEFT JOIN friendships f ON (f.sender_id=? AND f.receiver_id=p.id) OR (f.receiver_id=? AND f.sender_id=p.id) WHERE p.id!=? AND (p.handle LIKE ? ESCAPE '!' OR lower(p.name) LIKE ? ESCAPE '!') ORDER BY p.handle LIMIT 20`).bind(id,id,id,like,like).all();return {players:rows.results};}
 if(action==='player'){const handle=url.searchParams.get('handle')||'';const p=await db.prepare(`SELECT ${pub} FROM players p WHERE p.handle=?`).bind(handle).first<{id:string}>();if(!p)throw new InputError('Player not found.',404);return {player:p,stats:await stats(db,p.id)};}
 if(action==='leaderboard'){const mode=url.searchParams.get('mode')||'all',period=url.searchParams.get('period')||'all',scope=url.searchParams.get('scope')||'all';if(!['all','practice','ffa','duel'].includes(mode)||!['all','week'].includes(period)||!['all','friends'].includes(scope))throw new InputError('Invalid leaderboard filter.');const page=Math.max(0,Math.min(100,Number(url.searchParams.get('page'))||0))|0;const since=period==='week'?Date.now()-7*86400000:0;const condition="m.status='completed' AND m.finished_at>=? AND (?='all' OR m.mode=?) AND (?='all' OR p.id=? OR EXISTS (SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.sender_id=? AND f.receiver_id=p.id) OR (f.receiver_id=? AND f.sender_id=p.id))))";const args=[since,mode,mode,scope,id,id,id];const rows=await db.prepare(`SELECT p.id,p.handle,p.name,p.color,COUNT(*) AS matches,SUM(m.kills) AS kills,SUM(m.deaths) AS deaths,SUM(m.won) AS wins,SUM(m.kills)*10+SUM(m.won)*100 AS points FROM matches m JOIN players p ON p.id=m.player_id WHERE ${condition} GROUP BY p.id ORDER BY points DESC,kills DESC,p.handle ASC LIMIT 25 OFFSET ?`).bind(...args,page*25).all();const total=await db.prepare(`SELECT COUNT(DISTINCT p.id) AS count FROM matches m JOIN players p ON p.id=m.player_id WHERE ${condition}`).bind(...args).first<{count:number}>();return {players:rows.results,total:total?.count||0,page};}
 throw new InputError('Unknown view.',404);
}
export async function mutate(db:D1Database,id:string,body:Record<string,unknown>){const action=String(body.action);const now=Date.now();
 if(action==='profile'){const p=validateProfile(body);try{await db.prepare('UPDATE players SET handle=?,name=?,bio=?,color=? WHERE id=?').bind(p.handle,p.name,p.bio,p.color,id).run()}catch(e){if(String(e).includes('UNIQUE'))throw new InputError('That handle is already taken.',409);throw e}return {player:await db.prepare('SELECT * FROM players WHERE id=?').bind(id).first()};}
 if(action==='topup'){const amount=Number(body.amount);if(![2000,5000,10000].includes(amount))throw new InputError('Choose €20, €50 or €100 in demo credits.');const key='topup:'+id+':'+textValue(body.key,'Request key',8,80);const prior=await db.prepare('SELECT id FROM transactions WHERE id=? AND player_id=?').bind(key,id).first();if(prior)return state(db,id);await db.batch([db.prepare("INSERT INTO transactions (id,player_id,kind,amount,label,created_at) SELECT ?,?,'topup',?,'Demo credit top-up',? FROM players WHERE id=? AND balance+?<=100000 AND NOT EXISTS (SELECT 1 FROM matches WHERE player_id=? AND status='active')").bind(key,id,amount,now,id,amount,id),db.prepare('UPDATE players SET balance=balance+? WHERE id=? AND EXISTS (SELECT 1 FROM transactions WHERE id=?)').bind(amount,id,key)]);const inserted=await db.prepare('SELECT id FROM transactions WHERE id=?').bind(key).first();if(!inserted)throw new InputError('Finish your active match first, or keep the balance below €1,000.',409);return state(db,id);}
 if(action==='friend_send'){const target=textValue(body.target,'Player',1,200);if(target===id)throw new InputError('You cannot add yourself.');const player=await db.prepare('SELECT id FROM players WHERE id=?').bind(target).first();if(!player)throw new InputError('Player not found.',404);const key=JSON.stringify([id,target].sort());const existing=await db.prepare('SELECT id FROM friendships WHERE id=?').bind(key).first();if(existing)throw new InputError('You already have a request or friendship with this player.',409);await db.prepare("INSERT INTO friendships (id,sender_id,receiver_id,status,created_at) VALUES (?,?,?,'pending',?)").bind(key,id,target,now).run();return {ok:true};}
 if(['friend_accept','friend_decline','friend_cancel','friend_remove'].includes(action)){const key=textValue(body.id,'Request',1,500);const f=await db.prepare('SELECT * FROM friendships WHERE id=?').bind(key).first<{sender_id:string;receiver_id:string;status:string}>();if(!f)throw new InputError('This request no longer exists.',404);if(action==='friend_accept'||action==='friend_decline'){if(f.receiver_id!==id||f.status!=='pending')throw new InputError('Only the recipient can answer this request.',403)}else if(action==='friend_cancel'){if(f.sender_id!==id||f.status!=='pending')throw new InputError('You cannot cancel this request.',403)}else if(f.status!=='accepted'||(f.sender_id!==id&&f.receiver_id!==id))throw new InputError('You cannot remove this friendship.',403);if(action==='friend_accept')await db.prepare("UPDATE friendships SET status='accepted' WHERE id=? AND receiver_id=? AND status='pending'").bind(key,id).run();else await db.prepare('DELETE FROM friendships WHERE id=?').bind(key).run();return {ok:true};}
 if(action==='match_start'){const c=matchSetup(body),key=textValue(body.key,'Match key',8,80),matchId=id+':'+key;const existing=await db.prepare('SELECT * FROM matches WHERE id=? AND player_id=?').bind(matchId,id).first();if(existing)return {match:existing,player:await db.prepare('SELECT * FROM players WHERE id=?').bind(id).first()};const cost=c.mode==='duel'?1000:0,required=c.mode==='ffa'?c.rate*100:cost;try{await db.batch([db.prepare("INSERT INTO matches (id,player_id,mode,rate,team,started_at) SELECT ?,?,?,?,?,? FROM players WHERE id=? AND balance>=? AND NOT EXISTS (SELECT 1 FROM matches WHERE player_id=? AND status='active')").bind(matchId,id,c.mode,c.rate,c.team,now,id,required,id),db.prepare("UPDATE players SET balance=balance-? WHERE id=? AND EXISTS(SELECT 1 FROM matches WHERE id=? AND status='active')").bind(cost,id,matchId),db.prepare("INSERT INTO transactions (id,player_id,kind,amount,label,match_id,created_at) SELECT ?,?,'stake',?,'Duel stake reserved',?,? FROM matches WHERE id=? AND mode='duel'").bind('stake:'+matchId,id,-cost,matchId,now,matchId)])}catch(e){if(String(e).includes('UNIQUE'))throw new InputError('A match is already in progress.',409);throw e}const match=await db.prepare('SELECT * FROM matches WHERE id=?').bind(matchId).first();if(!match)throw new InputError('Insufficient credits or an unfinished match. Open your wallet to review.',409);return {match,player:await db.prepare('SELECT * FROM players WHERE id=?').bind(id).first()};}
 if(action==='match_finish'){const matchId=textValue(body.id,'Match',1,300);const match=await db.prepare('SELECT * FROM matches WHERE id=? AND player_id=?').bind(matchId,id).first<MatchRow>();if(!match)throw new InputError('Match not found.',404);if(match.status!=='active')return {match,...await state(db,id)};const player=await db.prepare('SELECT balance FROM players WHERE id=?').bind(id).first<{balance:number}>();if(!player)throw new InputError('Player not found.',404);const s=settlement(match,body,player.balance);const ledgerId='finish:'+match.id;await db.batch([db.prepare("INSERT INTO transactions (id,player_id,kind,amount,label,match_id,created_at) SELECT ?,?,'match',?,?,?,? FROM matches WHERE id=? AND player_id=? AND status='active'").bind(ledgerId,id,s.delta,s.reason,match.id,now,match.id,id),db.prepare("UPDATE players SET balance=balance+? WHERE id=? AND EXISTS (SELECT 1 FROM matches WHERE id=? AND status='active') AND EXISTS (SELECT 1 FROM transactions WHERE id=?)").bind(s.delta,id,match.id,ledgerId),db.prepare("UPDATE matches SET status=?,kills=?,deaths=?,score=?,enemy_score=?,won=?,delta=?,reason=?,finished_at=? WHERE id=? AND player_id=? AND status='active'").bind(s.status,s.kills,s.deaths,s.score,s.enemyScore,s.won?1:0,s.net,s.reason,now,match.id,id)]);return {match:await db.prepare('SELECT * FROM matches WHERE id=?').bind(match.id).first(),...await state(db,id)};}
 throw new InputError('Unknown action.',400);
}

